server:
  port: 8080
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 60s

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      password: ${REDIS_PASSWORD}

      db-index:
        auth: 0
        cache: 1

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  mail:
    host: ${EMAIL_HOST}
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  threads:
    virtual:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: ${DDL:validate}
    database: postgresql
    properties:
      hibernate:
        default_schema: public
        show_sql: true
        default_batch_fetch_size: 100

  jackson:
    property-naming-strategy: SNAKE_CASE

  elasticsearch:
    uris: ${ELASTICSEARCH_URIS}

jwt:
  header: ${JWT_HEADER}
  prefix: ${JWT_PREFIX}
  accessExp: ${JWT_ACCESS_TOKEN_TIME}
  refreshExp: ${JWT_REFRESH_TOKEN_TIME}
  secret: ${JWT_SECRET_KEY}